// Generated by build-pro-assets.py; PA-03 / NF-07.
export const PRO_CREDITS = [
  {
    author: 'Kenney',
    source: 'https://kenney.nl/assets/ui-pack-adventure',
    license: 'CC0-1.0',
  },
  {
    author: 'Kenney',
    source: 'https://kenney.nl/assets/animal-pack',
    license: 'CC0-1.0',
  },
  {
    author: 'para',
    source: 'https://opengameart.org/content/animated-particle-effects-1',
    license: 'CC0-1.0',
  },
  {
    author: 'Kenney',
    source: 'https://kenney.nl/assets/particle-pack',
    license: 'CC0-1.0',
  },
  {
    author: 'Kenney',
    source: 'https://kenney.nl/assets/casino-audio',
    license: 'CC0-1.0',
  },
  {
    author: 'Kenney',
    source: 'https://kenney.nl/assets/impact-sounds',
    license: 'CC0-1.0',
  },
  {
    author: 'Kenney',
    source: 'https://kenney.nl/assets/interface-sounds',
    license: 'CC0-1.0',
  },
  {
    author: 'ambientCG / Lennart Demes',
    source: 'https://ambientcg.com/view?id=Fabric037',
    license: 'CC0-1.0',
  },
  {
    author: 'ambientCG / Lennart Demes',
    source: 'https://ambientcg.com/view?id=Leather037',
    license: 'CC0-1.0',
  },
  {
    author: 'ambientCG / Lennart Demes',
    source: 'https://ambientcg.com/view?id=Metal034',
    license: 'CC0-1.0',
  },
  {
    author: 'ambientCG / Lennart Demes',
    source: 'https://ambientcg.com/view?id=Wood050',
    license: 'CC0-1.0',
  },
] as const;
export const PRO_ATTRIBUTION_URLS = PRO_CREDITS.map((item) => item.source);
