// Generated by build-pro-assets.py; PA-03 / NF-07.
export const PRO_CREDITS = [
  {
    author: 'para',
    source: 'https://opengameart.org/content/animated-particle-effects-1',
    license: 'CC0-1.0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    changes:
      'Resize, palette grading, normal-light bake where supplied, atlas packing or audio transcoding.',
  },
  {
    author: 'Kenney',
    source: 'https://kenney.nl/assets/particle-pack',
    license: 'CC0-1.0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    changes:
      'Resize, palette grading, normal-light bake where supplied, atlas packing or audio transcoding.',
  },
  {
    author: 'Kenney',
    source: 'https://kenney.nl/assets/casino-audio',
    license: 'CC0-1.0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    changes:
      'Resize, palette grading, normal-light bake where supplied, atlas packing or audio transcoding.',
  },
  {
    author: 'Kenney',
    source: 'https://kenney.nl/assets/impact-sounds',
    license: 'CC0-1.0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    changes:
      'Resize, palette grading, normal-light bake where supplied, atlas packing or audio transcoding.',
  },
  {
    author: 'Kenney',
    source: 'https://kenney.nl/assets/interface-sounds',
    license: 'CC0-1.0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    changes:
      'Resize, palette grading, normal-light bake where supplied, atlas packing or audio transcoding.',
  },
  {
    author: 'ambientCG / Lennart Demes',
    source: 'https://ambientcg.com/view?id=Fabric037',
    license: 'CC0-1.0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    changes:
      'Resize, palette grading, normal-light bake where supplied, atlas packing or audio transcoding.',
  },
  {
    author: 'ambientCG / Lennart Demes',
    source: 'https://ambientcg.com/view?id=Leather037',
    license: 'CC0-1.0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    changes:
      'Resize, palette grading, normal-light bake where supplied, atlas packing or audio transcoding.',
  },
  {
    author: 'ambientCG / Lennart Demes',
    source: 'https://ambientcg.com/view?id=Metal034',
    license: 'CC0-1.0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    changes:
      'Resize, palette grading, normal-light bake where supplied, atlas packing or audio transcoding.',
  },
  {
    author: 'ambientCG / Lennart Demes',
    source: 'https://ambientcg.com/view?id=Wood050',
    license: 'CC0-1.0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    changes:
      'Resize, palette grading, normal-light bake where supplied, atlas packing or audio transcoding.',
  },
  {
    author:
      'Katsushika Hokusai / The Metropolitan Museum of Art, JP660 (The Francis Lathrop Collection, Purchase, Frederick C. Hewitt Fund, 1911)',
    source: 'https://www.metmuseum.org/art/collection/search/37107',
    license: 'CC0-1.0',
    licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    changes: 'Public domain woodblock print; cropped, ink/paper duotone, resized and encoded.',
  },
  {
    author: 'Spen\u0109jo; Marcus Richert; based on Hanafuda graphics by Louie Mantia, Jr.',
    source: 'https://commons.wikimedia.org/wiki/File:Hwatu_January_Hikari.svg',
    license: 'CC-BY-SA-4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    changes:
      'Existing svgo-optimized Hwatu SVG: motif crop, circular mask, ink/paper duotone, resize. Derivative licensed CC BY-SA 4.0.',
  },
  {
    author: 'Spen\u0109jo; Marcus Richert; based on Hanafuda graphics by Louie Mantia, Jr.',
    source: 'https://commons.wikimedia.org/wiki/File:Hwatu_February_Tane.svg',
    license: 'CC-BY-SA-4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    changes:
      'Existing svgo-optimized Hwatu SVG: motif crop, circular mask, ink/paper duotone, resize. Derivative licensed CC BY-SA 4.0.',
  },
  {
    author: 'Spen\u0109jo; Marcus Richert; based on Hanafuda graphics by Louie Mantia, Jr.',
    source: 'https://commons.wikimedia.org/wiki/File:Hwatu_March_Hikari.svg',
    license: 'CC-BY-SA-4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    changes:
      'Existing svgo-optimized Hwatu SVG: motif crop, circular mask, ink/paper duotone, resize. Derivative licensed CC BY-SA 4.0.',
  },
  {
    author: 'Spen\u0109jo; Marcus Richert; based on Hanafuda graphics by Louie Mantia, Jr.',
    source: 'https://commons.wikimedia.org/wiki/File:Hwatu_April_Tane.svg',
    license: 'CC-BY-SA-4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    changes:
      'Existing svgo-optimized Hwatu SVG: motif crop, circular mask, ink/paper duotone, resize. Derivative licensed CC BY-SA 4.0.',
  },
  {
    author: 'Spen\u0109jo; Marcus Richert; based on Hanafuda graphics by Louie Mantia, Jr.',
    source: 'https://commons.wikimedia.org/wiki/File:Hwatu_May_Tane.svg',
    license: 'CC-BY-SA-4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    changes:
      'Existing svgo-optimized Hwatu SVG: motif crop, circular mask, ink/paper duotone, resize. Derivative licensed CC BY-SA 4.0.',
  },
  {
    author: 'Spen\u0109jo; Marcus Richert; based on Hanafuda graphics by Louie Mantia, Jr.',
    source: 'https://commons.wikimedia.org/wiki/File:Hwatu_June_Tane.svg',
    license: 'CC-BY-SA-4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    changes:
      'Existing svgo-optimized Hwatu SVG: motif crop, circular mask, ink/paper duotone, resize. Derivative licensed CC BY-SA 4.0.',
  },
  {
    author: 'Spen\u0109jo; Marcus Richert; based on Hanafuda graphics by Louie Mantia, Jr.',
    source: 'https://commons.wikimedia.org/wiki/File:Hwatu_July_Tane.svg',
    license: 'CC-BY-SA-4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    changes:
      'Existing svgo-optimized Hwatu SVG: motif crop, circular mask, ink/paper duotone, resize. Derivative licensed CC BY-SA 4.0.',
  },
  {
    author: 'Spen\u0109jo; Marcus Richert; based on Hanafuda graphics by Louie Mantia, Jr.',
    source: 'https://commons.wikimedia.org/wiki/File:Hwatu_August_Tane.svg',
    license: 'CC-BY-SA-4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    changes:
      'Existing svgo-optimized Hwatu SVG: motif crop, circular mask, ink/paper duotone, resize. Derivative licensed CC BY-SA 4.0.',
  },
  {
    author: 'Spen\u0109jo; Marcus Richert; based on Hanafuda graphics by Louie Mantia, Jr.',
    source: 'https://commons.wikimedia.org/wiki/File:Hwatu_September_Tane.svg',
    license: 'CC-BY-SA-4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    changes:
      'Existing svgo-optimized Hwatu SVG: motif crop, circular mask, ink/paper duotone, resize. Derivative licensed CC BY-SA 4.0.',
  },
  {
    author: 'Spen\u0109jo; Marcus Richert; based on Hanafuda graphics by Louie Mantia, Jr.',
    source: 'https://commons.wikimedia.org/wiki/File:Hwatu_October_Tane.svg',
    license: 'CC-BY-SA-4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    changes:
      'Existing svgo-optimized Hwatu SVG: motif crop, circular mask, ink/paper duotone, resize. Derivative licensed CC BY-SA 4.0.',
  },
  {
    author: 'Spen\u0109jo; Marcus Richert; based on Hanafuda graphics by Louie Mantia, Jr.',
    source: 'https://commons.wikimedia.org/wiki/File:Hwatu_November_Hikari.svg',
    license: 'CC-BY-SA-4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    changes:
      'Existing svgo-optimized Hwatu SVG: motif crop, circular mask, ink/paper duotone, resize. Derivative licensed CC BY-SA 4.0.',
  },
  {
    author: 'Spen\u0109jo; Marcus Richert; based on Hanafuda graphics by Louie Mantia, Jr.',
    source: 'https://commons.wikimedia.org/wiki/File:Hwatu_December_Tane.svg',
    license: 'CC-BY-SA-4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    changes:
      'Existing svgo-optimized Hwatu SVG: motif crop, circular mask, ink/paper duotone, resize. Derivative licensed CC BY-SA 4.0.',
  },
] as const;
export const PRO_ATTRIBUTION_URLS = PRO_CREDITS.flatMap((item) => [item.source, item.licenseUrl]);
