"""PA-03: pinned Docker tools; offline conversion, provenance and byte inventory."""
from pathlib import Path
from PIL import Image, ImageOps, ImageChops
import hashlib, json, subprocess, tempfile
ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / 'assets-src'
OUT = ROOT / 'public/pro'
OUT.mkdir(parents=True, exist_ok=True)
manifest = json.loads((SRC / 'manifest.json').read_text())
catalog = {}
notices = []
for item in manifest:
    source = SRC / item['file']
    assert hashlib.sha256(source.read_bytes()).hexdigest() == item['sha256'], source
    notices.append({k:item[k] for k in ['id','author','license','source','sha256','file']})
    if item['kind'] == 'map': continue
    id = item['id']
    record = {'group':item['group'], 'variants':[]}
    if item['kind'] == 'audio':
        for ext, codec in [('ogg',['-c:a','libvorbis','-q:a','4']),('m4a',['-c:a','aac','-b:a','96k','-movflags','+faststart'])]:
            target = OUT / f'{id}.{ext}'
            subprocess.run(['ffmpeg','-hide_banner','-loglevel','error','-y','-i',str(source),'-ac','1','-ar','44100',*codec,str(target)],check=True)
            record['variants'].append({'url':f'/pro/{target.name}','bytes':target.stat().st_size,'format':ext,'scale':1,'width':0,'height':0})
    else:
        original = Image.open(source).convert('RGBA')
        if id == 'felt':
            # Professional fabric albedo + supplied normal/roughness, baked once; no runtime shader.
            normal = SRC / item['file'].replace('_Color','_NormalGL')
            gray = ImageOps.grayscale(original)
            if normal.exists():
                light = Image.open(normal).convert('RGB').getchannel('G')
                gray = ImageChops.multiply(gray,light.point(lambda v: int(160+v*95/255)))
            original = ImageOps.colorize(gray,'#071914','#417c64').convert('RGBA')
        if id == 'wood':
            original = ImageOps.colorize(ImageOps.grayscale(original),'#100d0c','#79604a').convert('RGBA')
        if item['kind']=='atlas':
            # Original 8x8 animation: preserve all 64 frames and transparent edge, repack each tier.
            record['frames']=64; record['columns']=8
        for scale in [1,2,3]:
            side = min(item['base']*scale*(8 if item['kind']=='atlas' else 1),max(original.size))
            im=original.copy();im.thumbnail((side,side),Image.Resampling.LANCZOS)
            for ext in ['webp','avif']:
                target=OUT/f'{id}-{scale}x.{ext}'
                if ext=='webp':im.save(target,quality=88,method=6)
                else:
                    with tempfile.NamedTemporaryFile(suffix='.png') as tmp:
                        im.save(tmp.name);subprocess.run(['avifenc','--jobs','2','--speed','8','--min','20','--max','30',tmp.name,str(target)],check=True,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
                record['variants'].append({'url':f'/pro/{target.name}','bytes':target.stat().st_size,'format':ext,'scale':scale,'width':im.width,'height':im.height})
        catalog[id]=record
    catalog[id]=record
# Atlas packing of professionally drawn individual particles (no new painted shapes).
particles=[x for x in manifest if x['kind']=='particle']
atlas=Image.new('RGBA',(128*len(particles),128))
rects={}
for n,item in enumerate(particles):
    im=Image.open(SRC/item['file']).convert('RGBA');im.thumbnail((128,128),Image.Resampling.LANCZOS)
    atlas.paste(im,(n*128,0));rects[item['id']]={'x':n*128,'y':0,'width':im.width,'height':im.height}
atlas.save(OUT/'particles.webp',quality=90)
(OUT/'particles.json').write_text(json.dumps(rects,indent=2)+'\n')
(ROOT/'src/pro-assets/catalog.json').write_text(json.dumps(catalog,indent=2)+'\n')
# Credits are displayed text, never requested remotely. Exact source allowlist for NF-01 scanner.
credits=list({(x['author'],x['source']):(dict(author=x['author'],source=x['source'],license=x['license'])) for x in notices}.values())
(ROOT/'src/pro-assets/credits.ts').write_text('// Generated by build-pro-assets.py; PA-03 / NF-07.\nexport const PRO_CREDITS = '+json.dumps(credits,indent=2)+' as const;\nexport const PRO_ATTRIBUTION_URLS = PRO_CREDITS.map((item) => item.source);\n')
# Markdown is local downloadable provenance, not a runtime network manifest.
(OUT/'NOTICE.md').write_text('# Professional assets / CC0-1.0\n\nResize, color grading, normal-light baking, atlas packing, WebP/AVIF and audio transcoding.\n\n'+'\n'.join(f"- {x['id']}: {x['author']} / {x['source']} / {x['license']} / SHA256 {x['sha256']} / original {x['file']}" for x in notices)+'\n')
report={'originalBytes':sum(x['bytes'] for x in manifest),'outputBytesExcludingReport':sum(p.stat().st_size for p in OUT.iterdir() if p.name != 'sizes.json'),'files':{p.name:p.stat().st_size for p in sorted(OUT.iterdir()) if p.name != 'sizes.json'}}
(OUT/'sizes.json').write_text(json.dumps(report,indent=2)+'\n')
print(json.dumps({k:v for k,v in report.items() if k!='files'}))

subprocess.run(['node',str(ROOT.parent.parent/'node_modules/prettier/bin/prettier.cjs'),'--write',str(ROOT/'src/pro-assets/catalog.json'),str(ROOT/'src/pro-assets/credits.ts')],check=True)
